# Burning Daylight Configuration File
# Author: Artificial-720
# For issues or suggestions, please submit them at: https://github.com/Artificial-720/burning-daylight/issues

# Join message
messages:
  first_join: "Welcome to the server for the first time!"
  join: |
    <gold><bold>Welcome to Burning Daylight!</bold></gold>
    
    <white><bold>Core Mechanics:</bold></white>
    <red>  - Sunburn Damage:</red> <white>Direct sunlight will damage you, so stay in the shade or underground!</white>
    <blue>  - Nighttime Safety:</blue> <white>You'll take less damage at night, so use it to your advantage.</white>
    <dark_aqua>  - Weather Protection:</dark_aqua> <white>Rainy or stormy weather also reduces sunlight damage—watch the skies!</white>
    <green>  - Special Sun Gear:</green> <white>Leather armor isn't just for style; it protects you from the sun's harsh rays.</white>

# Grace period before sun damage effect starts
grace_period:
  duration: 300 # Grace period in seconds
  notify_player: true # Notify the player when the grace period starts or ends
  apply_on:
    first_join: true  # Apply grace period only on the player's first join
    respawn: false    # Apply grace period on every respawn
  message:
    start: "<green>You have a 5-minute grace period where you are immune to sun damage. Good Luck!"
    end: "<red>Your grace period has ended. You can now take damage."

# Conditions where sun damage is prevented
damage_prevention:
  fire_resistance_potion: true # Prevent damage if the player has a fire resistance potion effect

# Damage amounts under various conditions (2 damage = 1 heart)
burn_damage:
  day: 2.0 # Damage during the day
  night: 1.0 # Damage during the night
  weather: 1.0 # Damage during weather

armor_behavior:
  # Whether to apply fire protection enchantment damage reduction to burning daylight damage
  enchantment_fire_protection: true
  # Multiply damage by this factor when wearing piece of armor
  # Example: Full leather
  # 0.25 + 0.25 + 0.25 + 0.25 = 1.00 or 100% damage reduction
  damage_reduciton:
    leather_armor: 0.25
    iron_armor: 0.0
    gold_armor: 0.0
    diamond_armor: 0.0
    netherite_armor: 0.0
  durability:
    day: true      # Apply durability damage to armor during day
    night: false   # Apply durability damage to armor during night
    weather: false # Apply durability damage to armor during weather

# Duration of sun damage effect in seconds
effect_duration: 5

# Exempt players are not effected by sun damage
exempt_players: []

# List of worlds where burning damage is enabled
enabled_worlds:
  - world
# Apply damage in the Nether (would only apply when on Nether roof)
# - world_nether
# Apply damage in the End
# - world_the_end

# More intensive logging
logging:
  enabled: false        # Enable plugin logging
  log_to_console: true  # Log events to the console
  log_to_chat: false    # Log events to the in game chat