# Burning Daylight Configuration File
# Author: Artificial-720
# For issues or suggestions, please submit them at: https://github.com/Artificial-720/burning-daylight/issues


# Grace period before sun damage effect starts
grace_period:
  duration: 300 # Grace period in seconds
  notify_player: true # Notify the player when the grace period starts or ends
  apply_on:
    first_join: true  # Apply grace period only on the player's first join
    respawn: false    # Apply grace period on every respawn
  message:
    start: "<green>You have a 5-minute grace period where you are immune to sun damage. Good Luck!"
    end: "<red>Your grace period has ended. You can now take damage."

# Conditions where sun damage is prevented
damage_prevention:
  nether: true # Prevent damage in the Nether (would only apply when on Nether roof)
  end: true    # Prevent damage in the End
  fire_resistance_potion: true # Prevent damage if the player has a fire resistance potion effect

# Damage amounts under various conditions (2 damage = 1 heart)
burn_damage:
  day:
    default: 2.0 # Damage during the day
    leather_armor: 1.0 # Damage during the day while wearing leather armor
  night:
    default: 1.0 # Damage during the night
    leather_armor: 0.0 # Damage during the night while wearing leather armor
  weather:
    default: 1.0 # Damage during weather
    leather_armor: 0.0 # Damage during weather while wearing leather armor

# Duration of sun damage effect in seconds
effect_duration: 5