# Burning Daylight Configuration File
# Author: Artificial-720
# For issues or suggestions, please submit them at: https://github.com/Artificial-720/burning-daylight/issues


# Grace period before sun damage effect starts
grace_period:
  duration: 300 # Grace period in seconds
  notify_player: true # Notify the player when the grace period starts or ends
  apply_on:
    first_join: true  # Apply grace period only on the player's first join
    respawn: false    # Apply grace period on every respawn
  message:
    start: "<green>You have a 5-minute grace period where you are immune to sun damage. Good Luck!"
    end: "<red>Your grace period has ended. You can now take damage."

# Duration of effects, specified in ticks (20 ticks = 1 second)
effect_duration_ticks: 100

# Damage amounts under various conditions (2 damage = 1 heart)
burn_damage_amounts:
  day: 2.0        # Damage during the day
  night: 1.0      # Damage during the night
  day_with_leather_armor: 1.0 # Damage during the day while wearing leather armor
  night_with_leather_armor: 0.0 # Damage during the night while wearing leather armor
