name: BurningDaylight
version: '${version}'
main: io.github.artificial720.burningDaylight.BurningDaylight
api-version: '${minecraft_version}'
load: STARTUP
author: '${author}'
description: '${description}'